<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CBT WEB APP</title>
    <meta name="author" content="Shoetan Hassan Ayomide">
    <meta name="description" content="This website is a CBT-WEB-APP for schools and universities">
    <meta name="keywords" content="Html css js cbt php sql">
    <link rel="shortcut icon" href="/folder_A/IMAGE/lasuLogo.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
   <link rel="stylesheet" href="/CSS_FILES/studentlogin.css">
     
    
</head>
<body>
    <section class="general" id="general">
        <section class="sec_general">
            <nav class="header">
                <div><img src="/IMAGE_FILES/download.jfif" alt="school_logo" width="50px" height="50px"></div>
                <div><span class="add"><h1><b><span id="school_name">Fumac International School</span>  --- Virtual Learning And Assessment Platform --- <span id="short_school_name">(FUMAC-VLAP).</span></b></h1></span></div>
                <div><img src="/IMAGE_FILES/download.jfif" alt="school_logo" width="50px" id="img2" height="50px"></div>
            </nav>

            <div class="going_going">
                    <p>  <b>Motto: <i id="s_motto">Education Towards Positive Change.</i></b></p>
                    <p><b>Address: <i id="S_address">12,Salvation Avenue , Peace Estate, Zone D, Phase II, Ipaye B/Stop, Iba Road, Lagos.</i></b></p>
                    <p><b>Tel: <i id="s_tel">07081654727, 09068508072.</i></b></p>     
            </div>
 